smarthomej/addons

- .travis.yml
- buildci.sh
> [infrastructure] Enable Travis

- bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/DeconzBaseThingHandler.java
- bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/DeconzBridgeHandler.java
- bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/netutils/WebSocketConnection.java
- bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/netutils/WebSocketConnectionListener.java
In case the system goes into sleep mode the websocket connection can die without a disconnect message. This adds a watdchdof timer that resets the connection if no message is received after 120s (which is very unlikely).
> [deconz] Fix missing re-connect on dying websocket connections

- bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/SmartHomeDeviceHandler.java
- bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonSmartHomeCapabilities.java
- bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonSmartHomeDeviceAlias.java
- bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonSmartHomeDeviceNetworkState.java
- bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonSmartHomeGroupIdentifiers.java
- bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonSmartHomeGroupIdentity.java
- bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/jsons/JsonSmartHomeGroups.java
Should fix the issue reported in https://community.openhab.org/t/amazonechocontrol-cycles-rapidly-between-unknown-and-online-snapshot-3-1-binding/115811 and improves debug logging in case it does not.
> [amazonechocontrol] fix group device not updating state

- bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
- bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java
added: missing part to refresh hdmi
> [androiddebugbridge] Missing part to refresh hdmi

- bundles/org.smarthomej.binding.irobot/src/main/java/org/smarthomej/binding/irobot/internal/handler/RoombaHandler.java
In older (<3.1) versions of openHAB core the wrong QoS level was sent (0 instead of 1 and vice-versa). After this has been fixed the QoS send in the binding needs to be adapted. 
> [irobot] fix MQTT QoS on newer openHAB cores

- bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
added: missing return of the method (accidentally removed)
> [androiddebugbridge] missing return of the method

- bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
- bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java
Add fallback to the start package channel, using monkey command to open applications instead of am on devices which doesn't support the -n parameter (devices under android 8).
> [androiddebugbridge] add fallback to start package channel

- bundles/pom.xml
This enables correct javadoc generation for bundles that contain public/exported classes. Activation by putting an empty  `javadoc.profile` file in the root directoyr of the bundle.
> [infrastructure] fix javadoc generation

- README.md
> [infrastructure] add compatibility matrix

- bundles/org.smarthomej.binding.tr064/README.md
- bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/Tr064BindingConstants.java
- bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/Tr064RootHandler.java
- bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/config/Tr064RootConfiguration.java
- bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/phonebook/Tr064PhonebookImpl.java
- bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/soap/SOAPConnector.java
- bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/soap/SOAPValueConverter.java
- bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/util/SCPDUtil.java
- bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/util/Util.java
- bundles/org.smarthomej.binding.tr064/src/main/resources/OH-INF/thing/thing-types.xml
Issue reported in private mail
> [tr064] make SOAP timeout configurable

- bundles/org.smarthomej.binding.androiddebugbridge/README.md
- bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeBindingConstants.java
- bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
- bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java
- bundles/org.smarthomej.binding.androiddebugbridge/src/main/resources/OH-INF/thing/thing-types.xml
ported: shutdown channel
ported: tap event pattern
ported: some variable names
changed: mouse-tap channel to tap channel
changed: package name pattern for extended package names
ported from: https://github.com/openhab/openhab-addons/pull/10497
Also-By: Miguel <miguelwork92@gmail.com>
> [androiddebugbridge] shutdown channel, naming and improvements

- bundles/org.smarthomej.binding.mail/README.md
Mail actions have been renamed  in 11/20 to overcome limitations in core.  The documentation has not been properly amended.
> [mail] fix action documentation

- bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/dpt/KNXCoreTypeMapper.java
Currently only 22.101(RHCC status) and 22.1000 (KNX medium) are supprted by calimero. Both are mapped to strings.
> [knx] add support for DPT 22.xxxx

- bundles/org.smarthomej.binding.http/README.md
- bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/HttpHandlerFactory.java
- bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/HttpThingHandler.java
- bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/config/HttpThingConfig.java
- bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/http/RateLimitedHttpClient.java
- bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/http/RefreshingUrlCache.java
- bundles/org.smarthomej.binding.http/src/main/resources/OH-INF/thing/thing-types.xml
Jetty always sets the User-Agent header. Adding an additional User-Agent header with the `headers` configuration results in two User-Agent headers. This PR adds a new configuration parameter that sllows to set the User-Agent to an arbitrary value. There is no check if the setting is valid.
> [http] allow setting custom User-Agent header

- pom.xml
Because of the shutdown of Bintray/JCenter some dependencies were not available any longer. This resulted in build errors if the local maven repo did not contain those artifacts. This has been fixed in OHC 3.0.2.
> [infrastructure] upgrade OHC to 3.0.2 to fix build from scratch

- bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/phonebook/Tr064PhonebookImpl.java
- bundles/org.smarthomej.binding.tr064/src/test/java/org/smarthomej/binding/tr064/internal/phonebook/Tr064PhonebookImplTest.java
Because of a wrong regex the normalization for some phone numbers failed. This is fixed by the PR and also some tests are added.
> [tr064] fix phonebook lookup

- bundles/org.smarthomej.commons/README.md
- bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/ItemValueConverter.java
- bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/ItemValueConverterChannelConfig.java
- bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/converter/AbstractTransformingItemConverter.java
- bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/converter/ImageItemConverter.java
- bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/itemvalueconverter/converter/AbstractTransformingItemConverterTest.java
A null value results in UNDEF posted to the channel, regardless of transformation settings. This is needed for the strict error handling in the HTTP binding.
> [commons] allow null values for ItemValueConverter

- bundles/org.smarthomej.binding.http/README.md
- bundles/org.smarthomej.binding.http/pom.xml
- bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/HttpBindingConstants.java
- bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/HttpStatusListener.java
- bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/HttpThingHandler.java
- bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/config/HttpThingConfig.java
- bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/http/HttpResponseListener.java
- bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/http/HttpStatusListener.java
- bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/http/RateLimitedHttpClient.java
- bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/http/RefreshingUrlCache.java
- bundles/org.smarthomej.binding.http/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.smarthomej.binding.http/src/main/resources/update/url.update
- bundles/org.smarthomej.binding.http/src/test/java/org/smarthomej/binding/http/AbstractWireMockTest.java
- bundles/org.smarthomej.binding.http/src/test/java/org/smarthomej/binding/http/RateLimitedHttpClientTest.java
- bundles/org.smarthomej.binding.http/src/test/java/org/smarthomej/binding/http/RefreshingUrlCacheTest.java
This enables the thing status (which was always "ONLINE") to be updated depending on the result of the last request. Also enables rate limits for sending commands (with priority over state requests).
> [http] enable thing status changes on request result

- bundles/org.smarthomej.binding.notificationsforfiretv/src/main/java/org/smarthomej/binding/notificationsforfiretv/internal/NotificationsForFireTVHandler.java
added: set thing status depending on the last request
Inspired by your last commit to the http binding.
What do you think about setting the thing status depending on the last request?
It also do a request without a real notification on binding initialisation.
> [notificationsforfiretv] thing status depending on the last request

- bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/itemvalueconverter/converter/NumberItemConverter.java
- bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/itemvalueconverter/converter/ConverterTest.java
After the upgrade to the new UoM library in core the tests fail. This is because `100°C` (i.e. without space) is now a valid value. Another issue is that instead on an `IllegalArgumentException`  now a `MeasurementParseException` is thrown. 
> [infrastructure] adapt to new UoM Library

- README.md
Because the UoM library was updated with breaking changes after the M4 release openhab 3.1.0.M4 is not supported by SmartHome/J addons. The main (3.1.x) branch is compatible up to openHAB 3.1.0.M3 and the 3.2.x branch is compatible with openHAB 3.1.0.SNAPSHOT > 2373.
> add M4 not supported note

- bundles/org.smarthomej.transform.math/NOTICE
- bundles/org.smarthomej.transform.math/README.md
- bundles/org.smarthomej.transform.math/pom.xml
- bundles/org.smarthomej.transform.math/src/main/feature/feature.xml
- bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/binding/math/internal/AbstractMathTransformationService.java
- bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/binding/math/internal/AddTransformationService.java
- bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/binding/math/internal/MultiplyTransformationService.java
- bundles/org.smarthomej.transform.math/src/test/java/org/smarthomej/binding/math/internal/AddTransformationServiceTest.java
- bundles/org.smarthomej.transform.math/src/test/java/org/smarthomej/binding/math/internal/MultiplyTransformationServiceTest.java
- bundles/pom.xml
- Initial contribution of Math Transformation Service
The `ADD` transformation was deprecated for me when the Offset Profile has been introduced. But with the new Chain Profile it pops up in attention again.
I am using the `MULTIPLY` transformation to calculate energy consumption costs or carbon footprint.
I guess we can add related Profiles later.
> Initial contribution of Math Transformation Service

- bom/smarthomej-addons/pom.xml
- bundles/org.smarthomej.binding.http/src/main/java/org/smarthomej/binding/http/internal/HttpThingHandler.java
- bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/dpt/KNXCoreTypeMapper.java
- bundles/org.smarthomej.binding.notificationsforfiretv/src/main/java/org/smarthomej/binding/notificationsforfiretv/internal/NotificationsForFireTVHandler.java
- bundles/org.smarthomej.binding.onewire/src/main/java/org/smarthomej/binding/onewire/internal/device/DS2438.java
- bundles/org.smarthomej.binding.telenot/README.md
- add {} for if (http)
- remove unnecessary workaround in knx (already fixed in calimero 2.4)
- remove unused logger (notificationsforfiretv)
- fix local variable naming (onewire)
- fix markdown in documentation (telenot)
> fix spotless issues

- CODEOWNERS
- Added org.smarthomej.transform.basicprofiles to CODEOWNERS
> Added org.smarthomej.transform.basicprofiles to CODEOWNERS

- bundles/org.smarthomej.transform.math/README.md
- bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/binding/math/internal/AbstractMathTransformationService.java
- bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/binding/math/internal/DivideTransformationService.java
- bundles/org.smarthomej.transform.math/src/test/java/org/smarthomej/binding/math/internal/AddTransformationServiceTest.java
- bundles/org.smarthomej.transform.math/src/test/java/org/smarthomej/binding/math/internal/DivideTransformationServiceTest.java
- bundles/org.smarthomej.transform.math/src/test/java/org/smarthomej/binding/math/internal/MultiplyTransformationServiceTest.java
This is useful for e.g. to display the remaining time of the dishwasher in minutes instead of seconds. This could also be achieved by multiplying with `0.1666667` but having a dedicated transformation for that is more convenient.
> [transform.math] add divide

- bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/util/Util.java
> [tr064] improve channel parameter processing

- bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/Tr064RootHandler.java
As reported an updated user/password configuration is ignored until the whole system is restarted. This is because the SCPDUtil is only initialized if it is not set. The field was not nulled on disposal and thus the configuration change was ignored. 
> [tr064] fix ignored configuration update

- bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java
added: double check result before update state
I recognised that some devices have some state fluctuations and the state turns to on although it is still off.
It seems Miguel already recognised this behavior and added another workaround to the binding in the openHAB project.
I prefer to do the double check of the result in the "handleCommandInternal"-method instead of the "refreshStatus"-method.
Signed-off-by: Tom Blum trinitus01@googlemail.com
> [androiddebugbridge] double check result before update state 

- bundles/org.smarthomej.transform.basicprofiles/README.md
- bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/config/DebounceCountingStateProfileConfig.java
- bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/factory/BasicProfilesFactory.java
- bundles/org.smarthomej.transform.basicprofiles/src/main/java/org/smarthomej/transform/basicprofiles/internal/profiles/DebounceCountingStateProfile.java
- bundles/org.smarthomej.transform.basicprofiles/src/main/resources/OH-INF/config/debounce.xml
- bundles/org.smarthomej.transform.basicprofiles/src/main/resources/OH-INF/i18n/basicprofiles.properties
- bundles/org.smarthomej.transform.basicprofiles/src/main/resources/OH-INF/i18n/basicprofiles_de.properties
- bundles/org.smarthomej.transform.basicprofiles/src/test/java/org/smarthomej/transform/basicprofiles/internal/factory/BasicProfilesFactoryTest.java
- bundles/org.smarthomej.transform.basicprofiles/src/test/java/org/smarthomej/transform/basicprofiles/internal/profiles/DebouncCountingStateProfileTest.java
- Added Debounce Profile - Counting Strategy
This is a basic approach to debounce a state update via counting strategy. As mentioned in the related OHC issue there are other strategies to archive similar results too (e.g. time-based debouncing).
> [transform.basicprofiles] Added Debounce Profile - Counting Strategy

- bundles/org.smarthomej.binding.androiddebugbridge/README.md
- bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
- bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java
- bundles/org.smarthomej.binding.androiddebugbridge/src/main/resources/OH-INF/thing/thing-types.xml
- Reorder requests and reuse stored values
See https://github.com/smarthomej/addons/pull/112#discussion_r639213538
> [androiddebugbridge] Reorder requests and reuse stored values

- bundles/org.smarthomej.binding.deconz/README.md
- bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/dto/LightState.java
- bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/LightThingHandler.java
This fixes a regression introduced in https://github.com/openhab/openhab-addons/pull/9914 (window coverings do not support `ontime` and this stops the REST API from processing the request). This PR also changes from the deprecated bri/on to lift/open/stop. 
> [deconz] fix window covering support

- bundles/org.smarthomej.binding.snmp/README.md
- bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/SnmpTargetHandler.java
SNMP4J throws an IllegalArgumentException (e.g. when an engine is too short). This resulted in ERROR level log messages because initialization of the thing handler failed.
> [snmp] fix initialization exceptions

- bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
changed: exception handling
If a device is not connected it throws an exception.
But the binding still knows the device is not connected and shows it in the UI.
So there is no reason to throw any exception anymore.
Signed-off-by: Tom Blum trinitus01@googlemail.com
> [androiddebugbridge] exception handling

- bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/Tr064RootHandler.java
- bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/soap/SOAPValueConverter.java
- bundles/org.smarthomej.binding.tr064/src/main/resources/channels.xml
- bundles/org.smarthomej.binding.tr064/src/main/resources/xsd/channeltypes.xsd
As reported the values for upstream/downstream noise margin and attenuation were wrong by a factor of 10. The reason is that AVM reports 0.1 dB instead of the used dB.
> [tr064] fix noise margin and attenuation values

- bundles/org.smarthomej.binding.androiddebugbridge/README.md
- bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDynamicCommandDescriptionProvider.java
- bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java
- bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeHandlerFactory.java
- Added DynamicCommandOptionsProvider to populate 'start-package' Channel
This feature adds support for starting a package from the UI.
> [androiddebugbridge] Added DynamicCommandOptionsProvider to populate 'start-package' Channel

- bundles/org.smarthomej.binding.tr064/README.md
- bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/phonebook/Tr064PhonebookImpl.java
- bundles/org.smarthomej.binding.tr064/src/main/resources/OH-INF/config/phonebookProfile.xml
- bundles/org.smarthomej.binding.tr064/src/test/java/org/smarthomej/binding/tr064/internal/phonebook/Tr064PhonebookImplTest.java
Positive `matchCount` values match a defined number of digits from the right (end) of the phonenumber. Negative `matchCount` values skip digits from the left (e.g. for removing international or national prefixes).
> [tr064] allow skipping digits from left in phonebook lookup

- bundles/org.smarthomej.binding.amazonechocontrol/src/main/java/org/smarthomej/binding/amazonechocontrol/internal/handler/SmartHomeDeviceHandler.java
The code did not properly handle the case where the capability is present but not the individual device and thus cycled between UNKNOWNand ONLINE.
> [amazonechocontrol] fix cycling of UNKOWN/ONLINE for smarthome devices

- bundles/org.smarthomej.binding.mail/README.md
- bundles/org.smarthomej.binding.mail/pom.xml
- bundles/org.smarthomej.binding.mail/src/main/feature/feature.xml
- bundles/org.smarthomej.binding.mail/src/main/java/org/smarthomej/binding/mail/internal/MailBindingConstants.java
- bundles/org.smarthomej.binding.mail/src/main/java/org/smarthomej/binding/mail/internal/MailHandlerFactory.java
- bundles/org.smarthomej.binding.mail/src/main/java/org/smarthomej/binding/mail/internal/POP3IMAPHandler.java
- bundles/org.smarthomej.binding.mail/src/main/java/org/smarthomej/binding/mail/internal/config/POP3IMAPContentChannelConfig.java
- bundles/org.smarthomej.binding.mail/src/main/java/org/smarthomej/binding/mail/internal/config/POP3IMAPMailCountChannelConfig.java
- bundles/org.smarthomej.binding.mail/src/main/resources/OH-INF/i18n/mail_de.properties
- bundles/org.smarthomej.binding.mail/src/main/resources/OH-INF/thing/thing-types.xml
A new channel-type `content` allows the processing of mail contents. Mails can be filtered by subject and transformed before the item-state is updated.
This has been request in the German Facebook user group.
> [mail] add mail content processing

- features/smarthomej-addons/pom.xml
Create a .kar file that auto-installs the repomanager (so the content of the kar is available for UI installation via the addon provider).
> [distribution] create kar and fix auto-install

- bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDynamicCommandDescriptionProvider.java
- Added support for publishing `ChannelDescriptionChangedEvents`
Related to openhab/openhab-core#1505
> [androiddebugbridge] Added support for publishing ChannelDescriptionChangedEvents

- bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/DeconzBaseThingHandler.java
- bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/LightThingHandler.java
- bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/SensorBaseThingHandler.java
- bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/SensorThingHandler.java
This is a very nasty bug:
`thingEdited = thingEdited || addChannel` 
was optimized by the compiler in a way that `addChannel` was not called any more when `thingEdited` is already true. The result is that only the first channel is added. On next initialization the next channel is added (because the first is already present and `addChannel` returns false. This results in unnecessary consecutive thing updates.
> [deconz] fix thing update bug

- bundles/org.smarthomej.binding.snmp/README.md
- bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/SnmpTargetHandler.java
- bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/config/SnmpChannelConfiguration.java
- bundles/org.smarthomej.binding.snmp/src/main/java/org/smarthomej/binding/snmp/internal/config/SnmpInternalChannelConfiguration.java
- bundles/org.smarthomej.binding.snmp/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.smarthomej.binding.snmp/src/test/java/org/smarthomej/binding/snmp/internal/AbstractSnmpTargetHandlerTest.java
- bundles/org.smarthomej.binding.snmp/src/test/java/org/smarthomej/binding/snmp/internal/NumberChannelTest.java
- bundles/org.smarthomej.binding.snmp/src/test/java/org/smarthomej/binding/snmp/internal/SnmpTargetHandlerTest.java
- bundles/org.smarthomej.binding.snmp/src/test/java/org/smarthomej/binding/snmp/internal/SwitchChannelTest.java
This adds support for using units in the SNMP binding. If configured, the unit is added to the incoming value. Commands send to items are either stripped of their unit (if no unit configured for the channel) or converted to the condifured unit before sending.
> [snmp] add support for UoM

- pom.xml
After the release of openHAB 3.1.0 the core can be fixed and we can finally also release for the new OH core.
> [infrastructure] fix oh-core version

- bundles/org.smarthomej.binding.mail/pom.xml
- bundles/org.smarthomej.io.repomanager/pom.xml
The mail bundle did reference a wrong commons version and the repomanager had a not needed version in the pom
> fix versions in bundles

- bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/dpt/KNXCoreTypeMapper.java
- bundles/org.smarthomej.binding.knx/src/main/java/org/smarthomej/binding/knx/internal/handler/DeviceThingHandler.java
`UnDefType.UNDEF` is used to model the KNX command "incremental dimming/stop". In dimmer-control channels this has been properly processed, but in dimmer-channels this was not ignored but posted to the channel, leading to a wrong item state.
[openHAB #6970](https://github.com/openhab/openhab-addons/issues/6970)
> [knx] fix DPT 3.007 for dimmer channels

- bundles/org.smarthomej.binding.deconz/README.md
- bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/BindingConstants.java
- bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/dto/SensorConfig.java
- bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/dto/ThermostatUpdateConfig.java
- bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/SensorThermostatThingHandler.java
- bundles/org.smarthomej.binding.deconz/src/main/resources/OH-INF/thing/sensor-thing-types.xml
Some thermostats provide a keylock to protect the settings. The `locked` channel is added when available and is readable and writable.
> [deconz] add locked channel for thermostats

- bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/internal/InfluxDBConstants.java
- bundles/org.smarthomej.persistence.influxdb/src/main/java/org/smarthomej/persistence/influxdb/internal/influx2/InfluxDB2FilterCriteriaQueryCreatorImpl.java
- bundles/org.smarthomej.persistence.influxdb/src/test/java/org/smarthomej/persistence/influxdb/internal/InfluxFilterCriteriaQueryCreatorImplTest.java
Fixes bug in queries with InfluxDB 2.0 that had data migrated from InfluxDB 1.0 with old versions of the addon that didn't put item tag name.
Originally-by: Joan Pujol <joanpujol@gmail.com>
Original-PR: https://github.com/openhab/openhab-addons/pull/10937
> [influxdb] Fix queries for migrated databases

- bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/netutils/WebSocketConnection.java
Connections issues that do not contain a message are hard to fix. This adds the exception stack trace to the log message if no message is present to get a hint what went wrong.
> [deconz] improve logging

- bundles/org.smarthomej.binding.amazonechocontrol/README.md
- bundles/org.smarthomej.binding.amazonechocontrol/src/main/resources/OH-INF/thing/thing-types.xml
After recent changes it seems that Amazon has started to remove support for direct control of music providers. The `textCommand` can be used as a replacement.
> [amazonechocontrol] add deprecation warning for provider-specific channels

- bundles/org.smarthomej.binding.androiddebugbridge/pom.xml
- bundles/org.smarthomej.binding.androiddebugbridge/src/main/feature/feature.xml
- bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeBindingConstants.java
- bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
- bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java
- bundles/org.smarthomej.binding.androiddebugbridge/src/main/resources/OH-INF/thing/thing-types.xml
- bundles/org.smarthomej.binding.androiddebugbridge/src/main/resources/update/android.update
added: start intent channel
adb shell 'am start "intent:#Intent;scheme=customapp;package=com.comp.pac;end"'
Source: https://stackoverflow.com/questions/21034168/android-start-an-activity-from-command-line-using-intent-uri
> [androiddebugbridge] start intent channel

- bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/ColorUtil.java
- bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/GroupThingHandler.java
- bundles/org.smarthomej.binding.deconz/src/main/java/org/smarthomej/binding/deconz/internal/handler/LightThingHandler.java
- bundles/org.smarthomej.binding.deconz/src/test/java/org/smarthomej/binding/deconz/ColorUtilTest.java
This changes the HSB-XY conversion to the way Philips suggests for Hue. It also allows a future extension to use the Gamut of the device.
@ebaauw, is the credit given enough?
> [deconz] change XY conversion

- bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/UpdatingBaseBridgeHandler.java
- bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/UpdatingBaseThingHandler.java
- bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/impl/ThingUpdater.java
- bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/UpdatingBaseBridgeHandlerTest.java
- bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/UpdatingBaseThingHandlerTest.java
This fixes an issue during updating the thing structure. In some cases the thing handler was not properly assigned to the thing immediately after the update, resulting in problems when editing the thing configuration.
> [commons] fix thing handler missing

- bundles/org.smarthomej.binding.tr064/src/main/java/org/smarthomej/binding/tr064/internal/soap/SOAPValueConverter.java
A fixed value of 1s was used for TAM list retrieval while all other requests use the (user) defined value.
> [tr064] Fix timeout value not used for TAM lists

- bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/service/AbstractWatchService.java
- bundles/org.smarthomej.commons/src/main/java/org/smarthomej/commons/service/WatchQueueReader.java
- bundles/org.smarthomej.commons/src/test/java/org/smarthomej/commons/service/AbstractWatchServiceTest.java
- tools/static-code-analysis/checkstyle/rules.xml
The OHC version if the WatchQueueReader is not capable of having multiple listeners for the same directory. Since the PR with the fix was not accepted, a fixed version is added here.
> [commons] add a fixed version of the AbstractWatchService
